### ISSUE TITLE
Qwen-Image causes ComfyUI crash [Bug]

### ISSUE THREAD

**Issue by jano403** [nunchaku-tech/ComfyUI-nunchaku#468]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

When generating with Qwen-Image ComfyUI crashes. Flux.Dev and other nunchaku models work fine.

FULL COMFYUI LOG:
```
(venv) john@debian:~/TND/ComfyUI$ python main.py 
Checkpoint files will always be loaded safely.
Total VRAM 11907 MB, total RAM 64146 MB
pytorch version: 2.7.1+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch attention
Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0]
ComfyUI version: 0.3.50
ComfyUI frontend version: 1.25.9
[Prompt Server] web root: /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/comfyui_frontend_package/static
======================================== ComfyUI-nunchaku Initialization ========================================
Nunchaku version: 1.0.0.dev20250823
ComfyUI-nunchaku version: 1.0.0dev1
/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
=================================================================================================================
[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
Traceback (most recent call last):
  File "/home/john/TND/ComfyUI/nodes.py", line 2129, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 10, in <module>
    from .wanvideo.modules.model import rope_params
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/__init__.py", line 2, in <module>
    from .t5 import T5Decoder, T5Encoder, T5EncoderModel, T5Model
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/t5.py", line 11, in <module>
    from .tokenizers import HuggingfaceTokenizer
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/tokenizers.py", line 5, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

Cannot import /home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper module for custom nodes: No module named 'ftfy'

Import times for custom nodes:
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/comfyui-kjnodes
   0.1 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI_FluxMod
   0.6 seconds (IMPORT FAILED): /home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper
   1.3 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI-nunchaku

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load QwenImageTEModel_
loaded completely 10125.1125 7909.737449645996 True
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Requested to load NunchakuQwenImage
loaded completely 10167.674919891357 10165.506958007812 False
  0%|                                                                                                                                                                                                                   | 0/20 [00:00<?, ?it/s]terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7fbdda5785e8 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x7fbdda50d4a2 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x7fbdda9a5422 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x5bbcc (0x7fbdda9aabcc in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x5d440 (0x7fbdda9ac440 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4583b2 (0x7fbdcce583b2 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x7fbdda552f39 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x97a7bb (0x7fbd6f77a7bb in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x3351d41 (0x7fbd72151d41 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #9: <unknown function> + 0x337837f (0x7fbd7217837f in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #10: at::_ops::_cudnn_attention_forward::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, c10::SymInt, c10::SymInt, bool, double, bool, bool, std::optional<double>) + 0x31e (0x7fbdbb2a197e in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #11: at::native::_scaled_dot_product_cudnn_attention_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, bool, double, bool, bool, std::optional<double>) + 0x1ae (0x7fbd71e5fcde in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #12: <unknown function> + 0x3348138 (0x7fbd72148138 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #13: <unknown function> + 0x33481f8 (0x7fbd721481f8 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #14: at::_ops::_scaled_dot_product_cudnn_attention::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, bool, double, bool, bool, std::optional<double>) + 0x26a (0x7fbdbaffb9fa in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::native::scaled_dot_product_attention(at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, double, bool, std::optional<double>, bool) + 0xe7b (0x7fbdbab773cb in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x2c63446 (0x7fbdbb663446 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #17: at::_ops::scaled_dot_product_attention::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, double, bool, std::optional<double>, bool) + 0x25e (0x7fbdbaffac8e in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x59c937 (0x7fbdccf9c937 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #19: python() [0x547b96]
<omitting python frames>
frame #22: python() [0x584b24]
frame #23: python() [0x583b94]
frame #26: python() [0x584b24]
frame #27: python() [0x583b94]
frame #33: python() [0x5e4902]
frame #36: python() [0x584b24]
frame #37: python() [0x583b94]
frame #40: python() [0x584b24]
frame #41: python() [0x583b94]
frame #47: python() [0x5e4902]
frame #50: python() [0x584b24]
frame #51: python() [0x583b94]
frame #54: python() [0x584b24]
frame #55: python() [0x583b94]
frame #61: python() [0x5e4902]

Aborted

```

### Environment

Debian 12, Python 3.11, Pytorch 2.71cu128, cuda 12.8
GPU: RTX 3060 12GB,CPU: I5 12400F,RAM: 64GB DDR4

### Reproduction Steps

<img width="1835" height="980" alt="Image" src="https://github.com/user-attachments/assets/dbe4c22b-dd40-4ff6-999a-1c1a31140b52" />
Used default example workflow, only changed image size to 128x128, same issue with 1024x1024 and default size 1328x1328.

**Comment by jano403** [comment]
Additionally when trying to use --reserve-vram 8 for example, it also crashes but with different error:
**!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!**
```
python main.py --reserve-vram 8
Checkpoint files will always be loaded safely.
Total VRAM 11907 MB, total RAM 64146 MB
pytorch version: 2.7.1+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch attention
Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0]
ComfyUI version: 0.3.50
ComfyUI frontend version: 1.25.9
[Prompt Server] web root: /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/comfyui_frontend_package/static
======================================== ComfyUI-nunchaku Initialization ========================================
Nunchaku version: 1.0.0.dev20250823
ComfyUI-nunchaku version: 1.0.0dev1
/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
=================================================================================================================
[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg
Warning: Could not load sageattention: No module named 'sageattention'
sageattention package is not installed
Traceback (most recent call last):
  File "/home/john/TND/ComfyUI/nodes.py", line 2129, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/nodes.py", line 10, in <module>
    from .wanvideo.modules.model import rope_params
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/__init__.py", line 2, in <module>
    from .t5 import T5Decoder, T5Encoder, T5EncoderModel, T5Model
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/t5.py", line 11, in <module>
    from .tokenizers import HuggingfaceTokenizer
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/wanvideo/modules/tokenizers.py", line 5, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

Cannot import /home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper module for custom nodes: No module named 'ftfy'

Import times for custom nodes:
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.0 seconds: /home/john/TND/ComfyUI/custom_nodes/comfyui-kjnodes
   0.1 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI_FluxMod
   0.6 seconds (IMPORT FAILED): /home/john/TND/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper
   1.3 seconds: /home/john/TND/ComfyUI/custom_nodes/ComfyUI-nunchaku

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Using scaled fp8: fp8 matrix mult: False, scale input: False
Requested to load QwenImageTEModel_
loaded completely 9.5367431640625e+25 7909.737449645996 True
CLIP/text encoder model load device: cpu, offload device: cpu, current: cpu, dtype: torch.float16
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Requested to load NunchakuQwenImage
loaded partially 2349.2374198913567 2349.1357421875 0
  0%|                                                                                                                                                                                                                   | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/home/john/TND/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/john/TND/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/nodes.py", line 1521, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/nodes.py", line 1488, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 1150, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 1040, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 1025, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 993, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 976, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 755, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/k_diffusion/sampling.py", line 190, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 407, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 956, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 959, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 387, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 205, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 213, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/samplers.py", line 332, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/model_base.py", line 155, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/patcher_extension.py", line 111, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/model_base.py", line 194, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/comfy/ldm/qwen_image/model.py", line 430, in forward
    encoder_hidden_states, hidden_states = block(
                                           ^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/custom_nodes/ComfyUI-nunchaku/models/qwenimage.py", line 450, in forward
    img_mod_params = self.img_mod(temb)  # [B, 6*dim]
                     ^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/container.py", line 240, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/TND/ComfyUI/repositories/nunchaku/nunchaku/models/linear.py", line 186, in forward
    output.add_(self.bias.view(view_shape))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Prompt executed in 17.01 seconds
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f6350d785e8 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x7f6350d0d4a2 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3c2 (0x7f635d5a5422 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x5bbcc (0x7f635d5aabcc in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x5d440 (0x7f635d5ac440 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4583b2 (0x7f634fe583b2 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f6350d52f39 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x718398 (0x7f6350118398 in /home/john/TND/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: python() [0x50ace8]
frame #9: python() [0x630c37]
frame #10: python() [0x675b10]
frame #11: python() [0x53ad87]
<omitting python frames>
frame #16: python() [0x584b24]
frame #17: python() [0x583b68]
frame #18: python() [0x6793cc]
frame #19: python() [0x6543b4]
frame #20: <unknown function> + 0x891f5 (0x7f635f0fd1f5 in /lib/x86_64-linux-gnu/libc.so.6)
frame #21: <unknown function> + 0x10989c (0x7f635f17d89c in /lib/x86_64-linux-gnu/libc.so.6)

Aborted

```

**Comment by neozbr** [comment]
I'm getting exactly same error! gpu 3070 8gb, I hope there's a fix for this soon!
mine when it start the ksampler appear this error and disconnect, everytime!

<img width="899" height="440" alt="Image" src="https://github.com/user-attachments/assets/4728aee7-8b4d-41ec-a93e-fd8f85d57756" />

**Comment by kakaxixx** [comment]
qwen-image can't run, RuntimeError: CUDA error: an illegal memory access was encountered (at C:\Users\muyangl\actions-runner\_work\nunchaku\nunchaku\src\kernels\zgemm\gemm_w4a4_launch_impl.cuh:120)

**Comment by lmxyy** [comment]
Currently, Qwen-Image still requires 12-13G VRAM as ComfyUI does not natively support CPU offloading. We are currently implementing it. See [https://github.com/nunchaku-tech/nunchaku/pull/624](https://github.com/nunchaku-tech/nunchaku/pull/624)

**Comment by fredconex** [comment]
<img width="2478" height="1229" alt="Image" src="https://github.com/user-attachments/assets/77d0a8f5-77b9-4d50-b9f4-f1ea4a9f6870" />

I'm running on a 3080ti 12gb, it's also crashing for me, but there's seem to be no errors?

**Comment by neozbr** [comment]
sometimes the error appears , sometimes just shutdown , someone need to find a solution for this and fix...nunchuck its working ok on kontext only problem appears on qwen..

**Comment by neozbr** [comment]
> Currently, Qwen-Image still requires 12-13G VRAM as ComfyUI does not natively support CPU offloading. We are currently implementing it. See [nunchaku-tech/nunchaku#624](https://github.com/nunchaku-tech/nunchaku/pull/624)

no, its working for me without nunchuck perfect, on 3070 8gb,

**Comment by lmxyy** [comment]
which model are you using without nunchaku? I am not sure how ComfyUI manages the memory.

**Comment by iamrohitanshu** [comment]
> which model are you using without nunchaku? I am not sure how ComfyUI manages the memory.

@lmxyy most probably a GGUF. They work as they can be offloaded to RAM.

**Comment by w0ver** [comment]
same problem on my rtx3080

<img width="1919" height="914" alt="Image" src="https://github.com/user-attachments/assets/8442578e-f159-42a1-97f5-640d0af2118f" />

**Comment by solai25** [comment]
same problem, when it hit the ksampler comfyui crash

**Comment by Myoko** [comment]
waiting async offloading https://github.com/nunchaku-tech/nunchaku/pull/624

**Comment by 3qyemo** [comment]
<img width="2560" height="1400" alt="Image" src="https://github.com/user-attachments/assets/6d0f7638-34a3-40b1-abf1-08d574fc41c3" />The same error occurs: when it comes to the K sampler, comfyui crashes.

**Comment by duynt575** [comment]
Still crashes at Ksampler step with latest Nunchaku v1.0.0 (12GB of VRAM, 64GB of RAM, Windows 10).

**Comment by iamrohitanshu** [comment]
@duynt575 and @lmxyy Mine works. same config (12GB of VRAM, 64GB of RAM, Windows 10).
Though it says this in the log:

> Requested to load QwenImageTEModel_
> loaded completely 9.5367431640625e+25 7909.737449645996 True
> CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
> model weight dtype torch.bfloat16, manual cast: None
> model_type FLUX
> VRAM < 15GiB, enabling CPU offload
> Requested to load NunchakuQwenImage
> E:\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku\mixins\model.py:92: UserWarning: Skipping moving the model to GPU as offload is enabled
>   warn("Skipping moving the model to GPU as offload is enabled", UserWarning)

So, the **GPU stays almost empty and I guess it runs on RAM only**.
Also, I think Loras aren't supported yet.
I don't know what this line mean here -> `model_type FLUX`
Lastly, it doesn't work with RES4LYF sampler res_2d/bong_tangent. I haven't tried other samplers yet.

**Comment by duynt575** [comment]
@iamrohitanshu Here's my output:

```
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Using scaled fp8: fp8 matrix mult: False, scale input: False
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load QwenImageTEModel_
FETCH ComfyRegistry Data: 60/96
loaded completely 9825.8 7909.737449645996 True
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Requested to load NunchakuQwenImage
FETCH ComfyRegistry Data: 65/96
loaded completely 9606.858919891358 9605.954223632812 False
  0%|                                                                                                                       | 0/20 [00:00<?, ?it/s]
Q:\ComfyUI_windows_portable-nightly>pause
Press any key to continue . . .
```

I use 'nunchaku-1.0.0+torch2.8-cp312-cp312-win_amd64.whl' to install nunchaku.

**Comment by iamrohitanshu** [comment]
![Image](https://github.com/user-attachments/assets/d299aed9-e824-462f-af55-8ab1f836d99e)

Make sure you have the latest version of both nunchaku and the nunchaku custom node.
It was crashing for me as well, before I updated the custom nodes.
Also, I'm using `--force-upcast-attention` in the commandline args as qwen-image (even without nunchaku) gives me black images on my RTX 3060 12GB.

**Comment by duynt575** [comment]
@iamrohitanshu Thank you for the suggestion. I'm able to use it now after delete both nunchaku wheel folder and nunchaku custom node folder and reinstall them. But it's quite slow, about ~6.8s/it, the FP8 model gives ~8.4s/it. Then I notice that nunchaku only uses 2GB of VRAM out of 12GB, maybe that's the reason for the slow speed.

As for black images, if you use '--use-sage-attention' you will get black image. Just use Patch Sage Attention KJ node then it will work.

**Comment by lmxyy** [comment]
> [@iamrohitanshu](https://github.com/iamrohitanshu) Thank you for the suggestion. I'm able to use it now after delete both nunchaku wheel folder and nunchaku custom node folder and reinstall them. But it's quite slow, about ~6.8s/it, the FP8 model gives ~8.4s/it. Then I notice that nunchaku only uses 2GB of VRAM out of 12GB, maybe that's the reason for the slow speed.
> 
> As for black images, if you use '--use-sage-attention' you will get black image. Just use Patch Sage Attention KJ node then it will work.

You're probably using swap. See https://github.com/nunchaku-tech/ComfyUI-nunchaku/issues/527#issuecomment-3258055288

**Comment by sinand99** [comment]
@duynt575  @lmxyy  Even with Patch Sage Attention KJ node, I am getting black images no matter which option I select. Using the latest ComfyUI and Nunchaku with Sage Attention 2.2

**Comment by duynt575** [comment]
@lmxyy Thank you, adding 'num_blocks_on_gpu=xx' improves the speed but not much, from ~6.8s/it to ~6.2s/it (7GB of VRAM used, more will cause an OOM error at the VAE decoding step). I guess that's just the limitation of what my hardware can do. I'll stick to FP8 for now because I can use 4-step lora. The Nunchaku 4-step model doesn't work for me because it creates over-saturated images, most likely because of the default LoRA strength being 1.0. When using the FP8 version, I have to lower the lora strength value to about 0.45 to get a proper result.

@sinand99 I don't have black images if I don't run ComfyUI with the '--use-sage-attention' parameter and just use the node. You can try not using Sage at all to see if it works; if it does, then Sage is the culprit.

**Comment by iamrohitanshu** [comment]
> OOM error at the VAE decoding step

@duynt575 May be try `tiled VAE decoding`?

**Comment by lmxyy** [comment]
This issue should have been fixed in the official v1.0.0 release.
